version: '3.9'
services:
  app:
    build: .
    container_name: pdm-backend-server
    image: pdm-backend-server
    ports:
      - 2323:2323
    env_file:
      - .env
    depends_on:
      - postgres
      - influxdb

  postgres:
    image: postgres:15.1
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres

  influxdb:
    image: influxdb:2.6.1
    container_name: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: my-user
      DOCKER_INFLUXDB_INIT_PASSWORD: my-password
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-auth-token
    volumes:
      - influxdb-data:/data/influxdb

volumes:
  postgres-data:

  influxdb-data: